[project]
name = "langgraph-agent-building"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Yashendra Rajput", email = "100985842+Yashendra25@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "langchain>=1.4.0",
    "pydantic>=2.13.5",
]

[project.scripts]
langgraph-agent-building = "langgraph_agent_building:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
